runtime: python27
threadsafe: no
api_version: 1

handlers:
- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /_ah/xmpp/message/chat/
  script: xmpps/in_msg.py

- url: /.*
  script: webpart/web.py

inbound_services:
- xmpp_message